import Permission from '../Permission';
import AuthorizedRoute from './AuthorizedRoute';
import Secured from './Secured';
import check from './CheckPermissions';
import renderAuthorize from './renderAuthorize';
Permission.Secured = Secured;
Permission.AuthorizedRoute = AuthorizedRoute;
Permission.check = check;
const RenderAuthorize = renderAuthorize(Permission);
export default RenderAuthorize;
